### ISSUE TITLE
mod breaks worldedit gui tab in unified_inventory

### ISSUE THREAD

**Issue by verymilan** [minetest-monitoring/monitoring#12]
Hi there, i would like to report that as soon as this mod is part of the subgame, unified_inventory gets a little messed up, especially the worldedit gui tab:

![g3eash](https://user-images.githubusercontent.com/10698140/99145280-c860a600-266d-11eb-8ce9-7d4e9cf49575.JPG)

also hudbars got pushed a little to the left:

![j56r4w](https://user-images.githubusercontent.com/10698140/99145307-f5ad5400-266d-11eb-8f73-616416f51d6b.JPG)

**Comment by BuckarooBanzay** [comment]
Uhm, this is quite strange, the mod _does_ intercept some calls to the engine but it passes them through 1:1.
There are no formspec shenanigans in there :thinking:

What mods did you use? Are they public? Can you provide a repro?

**Comment by verymilan** [comment]
Thanks for your quick reply, most mods are public, some are temporarely behind a login-wall but i can grant you access ... this is our modlist: https://haste.tchncs.de/raw/zisodohosu ... and this is the git to our subgame: https://git.tchncs.de/Illuna-Minetest/minetest_game/tree/technicworld/

**Comment by BuckarooBanzay** [comment]
Turns out the result from the intercepted `on_player_receive_fields` calls did not get returned to the caller :facepalm: 
Thanks for reporting
