### ISSUE TITLE
A mod dashboard for Techage

### ISSUE THREAD

**Issue by Niklp-MT** [minetest-monitoring/monitoring#22]
Please make a dashboard for the Techage mod so monitoring_techage, similar to the Technic mod.

[](https://github.com/joe7575/techage)

**Comment by BuckarooBanzay** [comment]
Would be interesting, but i don't think the `techage` has any metrics exposed so far :thinking:

**Comment by joe7575** [comment]
> Would be interesting, but i don't think the techage has any metrics exposed so far

No, it hasn't. And that will be a challenge. Techage has about 150 timer functions/sources that you would need a wrapper for. 
For this we need a solution from the C++ code.

**Comment by Niklp-MT** [comment]
I think we can close the issue, it probably wouldn't be worth the effort over Lua.

**Comment by BuckarooBanzay** [comment]
> I think we can close the issue, it probably wouldn't be worth the effort over Lua.

Just fyi: luajit can handle that much function interception (and even much more) and posting the metrics isn't really heavyweight either.
There are currently over 200+ metrics exposed on pandorabox:

```bash
# curl https://monitoring.minetest.land/push/metrics | grep "\"pandorabox.io" | wc -l
226
```
Self-monitoring dashboard: https://monitoring.minetest.land/d/ZxCS-XGWz/self-monitoring?orgId=1&refresh=5s
