### ISSUE TITLE
add chat preview 

### ISSUE THREAD

**Issue by tigercoding56** [minetest-monitoring/monitoring#24]
it would be nice to have a element that shows the 20 most recent chat messages ( if there are any )

**Comment by BuckarooBanzay** [comment]
> it would be nice to have a element that shows the 20 most recent chat messages ( if there are any )

Uh, while this _could_ be done i don't think it should: this is a system/engine-monitoring tool not a moderation-tool.
There's also the privacy aspect in making chat-logs public :unamused:

**Comment by tigercoding56** [comment]
chat logs are already puplic anyone can just make a modded client that logs chat (and runs on a server ) my idea was to only show the last 20 messages in chat

------- Original Message -------

**Comment by BuckarooBanzay** [comment]
closing, this is out of scope for a monitoring mod
